Solution_4/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chat.urls', namespace='chat')),


]

chat/urls.py
from django.conf.urls import url
from chat.views import IndexView, loginView, registerView, chat_room
from django.contrib.auth.decorators import login_required
# As of Django 1.10 it is impossible to reference views as: 'django.contrib.auth.views.logout' but is required to call
# them directly.
from django.contrib.auth.views import logout

# Updated for Django 2.0 to fix namespace exception from the inc
app_name='chat'

urlpatterns = [
    # redirect_field_name=None prevents Django from redirecting back to where it was called from.
    url(r'^$', login_required(IndexView.as_view(),redirect_field_name=None), name= 'index'),
    url('^login/$', loginView, name= 'login'),
    url('^register/$', registerView, name= 'register'),
    # The use of builtin logout allows the use of 'next_page' which automatically redirects.
    url(r'^logout/$', logout, name= 'logout', kwargs={'next_page': '/chat/'}),
	# url(r'^logout/$', 'django.contrib.auth.views.logout', name= 'logout', kwargs={'next_page': '/chat/'}),
    url(r'^(?P<user_id>[0-9]+)/$', chat_room, name= 'room'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Message (models.Model):

    sender = models.ForeignKey(User, related_name='Sender', on_delete=models.CASCADE)
    mess_receiver = models.ForeignKey(User, related_name='Receiver', on_delete=models.CASCADE)
    content = models.CharField('Message', max_length=500)
    pub_date = models.DateTimeField('Date sent')

    def __str__(self):
        temp = 'Sent from: ' + self.sender.username + '\n' + 'Sent to: ' + self.mess_receiver.username + '\n'
        temp += self.content + '\n' + 'Sent on: ' + '{0}:{1}'.format(self.pub_date.hour, self.pub_date.minute)

        return temp

chat/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import User

# A form that will be used in the login screen.
class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    # Is called by .is_valid() and will return a dictionary(cleaned_data) of form members name and their values.
    def clean(self):
        # Check if both username and password are filled in the form.
        if all(key in self.cleaned_data for key in ('username', 'password')):
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            # Authenticate the username and password and then return cleaned_data.
            user = authenticate(username=username, password=password)
            if user is not None:
                return self.cleaned_data
        raise forms.ValidationError(r"Username and password are incorrect.")


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    pass_repeat = forms.CharField(widget=forms.PasswordInput(), label='Password again:')

    # Is called by .is_valid() and will return a dictionary(cleaned_data) of form members name and their values.
    def clean(self):
        # Check if username, password and pass_repeat are filled in the form.
        if all(key in self.cleaned_data for key in ('username', 'password', 'pass_repeat')):
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            pass_repeat = self.cleaned_data['pass_repeat']
            # Make sure both passwords are the same.
            if password != pass_repeat:
                raise forms.ValidationError(r"Passwords do not match.")
            # Make sure that the username doesn't exist already.
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(r"Username already used.")
            # If all passed then send the form data.
            return self.cleaned_data
        raise forms.ValidationError(r"Some of the fields were left empty.")


class MessageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea({'cols': 30, 'rows': 3}), label=False)

    # Is called by .is_valid() and will return a dictionary(cleaned_data) of form members name and their values.
    def clean(self):
        # If a message was written into the textarea then content will exist, otherwise it will not.
        if 'content' in self.cleaned_data:
            return self.cleaned_data
        raise forms.ValidationError(r"Must have text to send.")

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib.auth import login
from django.views import generic
from django.utils import timezone
from django.http import HttpResponseRedirect
from .forms import MessageForm, LoginForm, RegisterForm


def loginView(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # Form returned from clean() is returned already authenticated.
            user = User.objects.get(username=form.cleaned_data['username'])
            # Avoid the need to authenticate, due to the fact authentication is done in the form.
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)
            return HttpResponseRedirect(r'/chat/')
        # Error in username or password entered.
        return render(request, r'registration/login.html', {'form': LoginForm(), 'error': form.non_field_errors})
    # If the request wasn't made with post method.
    return render(request, r'registration/login.html', {'form': LoginForm()})


def registerView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            # Form returned from clean() is returned already authenticated.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # Form verifies username is not already used and passwords were entered correctly.
            user = User(username=username)
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(r'/chat/login/')
        return render(request, r'registration/register.html', {'form': RegisterForm(), 'error': form.non_field_errors})
    else:
        form = RegisterForm()
    return render(request, r'registration/register.html', {'form': form})


class IndexView(generic.ListView):
    template_name = 'chat/index.html'
    context_object_name = 'user_list'

    def get_queryset(self):
        return User.objects.all()

@login_required(redirect_field_name=None)
def chat_room(request, user_id):
    contact = get_object_or_404(User, id=user_id)
    context = {}
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            new_message = Message(sender=request.user, mess_receiver=contact,
                                  content=form.cleaned_data['content'], pub_date=timezone.now())
            new_message.save()
        else:
            context.update({'error': form.non_field_errors})

    message_list = Message.objects.filter((Q(sender=contact) & Q(mess_receiver=request.user))
                                          | (Q(mess_receiver=contact) & Q(sender=request.user))).order_by('pub_date')
    if message_list is not None:
        date = 0
        msg_list=[]
        for (i,message) in enumerate(message_list):
            if message.pub_date.date() != date:
                if message.pub_date.date() == timezone.now().date():
                    msg_list += ['\n\n<div class="Date">Today</div>']
                else:
                    msg_list += ['\n\n<div class="Date">' + '{}.{}.{}'.format(message.pub_date.day, message.pub_date.month,
                                                                              message.pub_date.year) + "</div>"]
                msg_list[i] += message.__str__().replace(request.user.username.__str__(), 'You', 1)
                date = message.pub_date.date()
            else:
                msg_list += ['\n\n' + message.__str__().replace(request.user.username.__str__(), 'You', 1)]

        # To replace the username of the current user with the word 'You' when chat displayed.
        message_list = msg_list
    context.update({'message_list': message_list, 'other': contact, 'form': MessageForm()})
    return render(request, r'chat/room.html', context)

chat/templates/chat/base.html
<html>
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}" />
    {% block head %} <title>{% block title %} {% endblock %}</title> {% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

chat/templates/chat/index.html
{% extends 'chat/base.html' %}
{% block title %}Index{% endblock %}
{% block body %}
    {% block header %}<h1> User list </h1> {% endblock %}
    {% block content %}
        {#        In Django, 'user' parameter will always be the registered user. So user.username gets the user's username. #}
        Welcome {{ user.username }}, you can <a href="{% url 'chat:logout' %}">logout</a>.
        {% for userl in user_list %}
            {#            Show all the users registered except the active one. #}
            {% if userl != user %}
                {#                Go to chat\urls.py and find 'room' url there, add user1.id as parameter to the function view. #}
                <br /> <a class="users" href="{% url 'chat:room' userl.id %}">{{ userl.username }}</a>
            {% endif %}
        {% endfor %}
    {% endblock %}
{% endblock %}

chat/templates/chat/room.html
{% extends 'chat/base.html' %}
{% block title %} Chat with {{ other.username }}{% endblock %}
{% block body %} Welcome {{ user.username }}, you can <a href="{% url 'chat:logout' %}">logout</a> here.
    <br /> You can also go back to the <a href="{% url 'chat:index' %}">homepage</a>.
    <br /><br />You are in chat with {{ other.username }}
    {% if message_list %}
        {% for message in message_list %}
            {#            autoescape off allows message to have some HTML code which will be added as original code. #}
            {#            linebreaksbr turns each \n in message into <br />#}
            {% autoescape off %} {{ message|linebreaksbr }} {% endautoescape %}
        {% endfor %}
    {% else %}
        {#        If there are no messages between the user and the other user. #}
        <br /><br /> You have no chat history with {{ other.username }}
    {% endif %}
    <hr />
    {#    Get all the errors in parameter error from loginView and remove all the tags it has.#}
    <p class="Error">{{ error|striptags }}</p>
    <form method="post" action="{% url 'chat:room' other.id %}">
        {# Because send_msg gets input except request, the user_username has to be added to the right of it as the input #}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send" />
    </form>
{% endblock  %}